<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use app\models\Cliente;
use app\models\Documento;
use app\models\TipoDocumento;
use app\models\NotaCredito;
use kartik\daterange\DateRangePicker;
use app\controllers\SiteController;


/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('documento', 'Document list');
$this->params['breadcrumbs'][] = $this->title;
$status = [ 2 => 'DOCUMENTO GENERADO', 3 => 'DOCUMENTO ANULADO'];
$primerDiaMes = date('01/MM/yyyy'); // hard-coded '01' for first day
$ultimoDiaMes  = date('dd/MM/yyyy');

$get = Yii::$app->request->get();
$rs = "";
$fecha = "";

if (!empty($get)) {
    if ( !empty($get['DocumentoSearch']['fecha_doc'])) {
        $fecha = $get['DocumentoSearch']['fecha_doc'];
    }

    if (!empty($fecha)) {
        $fechaDoc = explode(" - ", $fecha);
        $rs = "<br>" . Yii::t('app', 'From') . " " . $fechaDoc[0] . " ". Yii::t('app','to')." ". $fechaDoc[1];
    }
}

$pdfHeader = '
<table class="" style="">
    <tr>
        <td width="25%">
          <div class="rounded"> <img src="'.Url::to([SiteController::getEmpresa()->image_empresa]).'" width="180px"/> </div>
        </td>
        <td width="50%" align="center" >
          <div class="titulo-emp" style="font-size:20px;font-weight:bold;">' . SiteController::getEmpresa()->nombre_empresa . '</div><br>
          <div class="datos-emp">' . SiteController::getEmpresa()->direcc_empresa . '</div>
          <div class="datos-emp">' . SiteController::getEmpresa()->tlf_empresa . '</div>
          <div class="datos-emp">' . SiteController::getEmpresa()->movil_empresa . '</div>
          <div class="datos-emp">' . SiteController::getEmpresa()->correo_empresa . '</div>
        </td>
        <td width="25%" align="right">
            <b>' . Yii::t('app', 'Date') . ':</b> {DATE d/m/Y}
            <br>
            <b>' . Yii::t('app', 'Hour') . ':</b> {DATE H:i:s}
            <br>
            <b>' . Yii::t('app', 'Page') . ':</b> {PAGENO}/{nbpg}
        </td>
    </tr>
</table>
<hr>
<table width="100%">
<tr>
    <td colspan="3" style="text-align:center">
        <b>'. Yii::t('documento', 'Sales report'). '</b> <br>
        <b>'. $rs.'</b> <br>
    </td>
</tr>
</table>
';

$exportConfig = [
  GridView::EXCEL => [
        'label' => Yii::t('app', 'Excel'),
        'icon' => 'file-excel-o',
        'iconOptions' => ['class' => 'text-success'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('app', 'grid-export'),
        'alertMsg' => Yii::t('app', 'The EXCEL export file will be generated for download.'),
        'options' => ['title' => Yii::t('app', 'Microsoft Excel 95+')],
        'mime' => 'application/vnd.ms-excel',
        'config' => [
            'worksheet' => Yii::t('documento', 'Document list'),
            'cssFile' => ''
        ]
    ],
    GridView::PDF => [
        'label' => Yii::t('app', 'PDF'),
        'icon' =>  'file-pdf-o',
        'iconOptions' => ['class' => 'text-danger'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('app', 'grid-export'),
        'alertMsg' => Yii::t('app', 'The PDF export file will be generated for download.'),
        'options' => ['title' => Yii::t('app', 'Portable Document Format')],
        'mime' => 'application/pdf',
        'config' => [
            'mode' => 'c',
            'format' => 'A4-L',
            'destination' => 'I',
            'marginTop' => 60,
            'marginBottom' => 10,
            'cssFile' => '@webroot/css/rptCss.css',
            'methods' => [
                 'SetHeader' => $pdfHeader,
                'SetFooter' => "",
            ],
            'options' => [
                //'title' => $title,
                'subject' => Yii::t('app', 'PDF export generated by kartik-v/yii2-grid extension'),
                'keywords' => Yii::t('app', 'krajee, grid, export, yii2-grid, pdf')
            ],
            'contentBefore'=>'',
            'contentAfter'=>''
        ]
    ],
];
?>
    <div class="documento-index">

        <h1><?= Html::encode($this->title) ?></h1>
        <?php Pjax::begin(['id' => 'grid', 'timeout' => 3000]); ?>

        <p><?php  echo $this->render('_searchListadoFactura', ['model' => $searchModel]); ?></p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'showPageSummary' => true,
            'pjax' => true,
            'toolbar' => [
                '{export}',
                '{toggleData}'
            ],
            'export' => [
              'showConfirmAlert' => false,
            ],
            'exportConfig' => $exportConfig,
            'panel' => [
                'heading'=>'<h3 class="panel-title"><i class="fa fa-book"></i> ' . Yii::t('documento','Document list') . '</h3>',
            ],
            'columns' => [
                [
                  'value' => function ($data) {
                    return $data->numeracion->tipoDocumento->abrv_tipod.$data->numeracion->serie_num;
                  },
                  'hAlign' => 'center',
                  'vAlign' => 'middle',
                  'width' => '5%'
                ],
                [
                    'attribute' => 'cod_doc',

                    'hAlign' => 'center',
                    'vAlign' => 'middle',
                    //'width' => '%'
                ],
                [
                  //'width' => '9%',
                  'value' => function($data){
                       return Yii::$app->formatter->asDate($data->fecha_doc, 'dd/MM/yyyy');
                  },
                  'attribute' => 'fecha_doc',
                  'vAlign' => 'middle',
                ],
                [
                  'label' => 'DNI',
                  'value' => 'pedidoDoc.cltePedido.dni_clte',
                ],
                [
                  'label' => 'RUC',
                  'value' => 'pedidoDoc.cltePedido.ruc_clte',
                ],
                [
                    'attribute' => 'cliente',
                    'label' => Yii::t('cliente','Customer'),
                    'value' => 'pedidoDoc.cltePedido.nombre_clte',
                    'width' => '18%',
                    'hAlign' => 'left',
                    'vAlign' => 'middle',
                    'pageSummary' => Yii::t('app','Page Summary'),
                    'pageSummaryOptions' => ['class' => 'text-left'],
                ],
                [
                    'attribute' => 'tipoDocumento',
                    'label' => Yii::t('tipo_documento','Document type'),
                    'value' => 'tipoDoc.des_tipod',
                    'hAlign' => 'left',
                    'vAlign' => 'middle',
                    //'width' => '15%',
                    'group' => true,  // enable grouping
                    'groupedRow' => true,                    // move grouped column to a single grouped row
                    'groupOddCssClass' => 'kv-grouped-row',  // configure odd group cell css class
                    'groupEvenCssClass' => 'kv-grouped-row', // configure even group cell css class
                    'groupFooter' => function ($model, $key, $index, $widget) { // Closure method
                        return [
                            'mergeColumns' => [[0,7]], // columns to merge in summary
                            'content' => [             // content to show in each summary cell
                                1 => 'Summary (' . $model->tipoDoc->des_tipod . ')',
                                8 => GridView::F_SUM,
                                9 => GridView::F_SUM,
                            ],
                            'contentFormats' => [      // content reformatting for each summary cell
                                8 => ['format' => 'number', 'decimals' => 2],
                                9 => ['format' => 'number', 'decimals' => 2],
                            ],
                            'contentOptions' => [      // content html attributes for each summary cell
                                1 => ['style' => 'font-variant:small-caps'],
                                8 => ['style' => 'text-align:right'],
                                9 => ['style' => 'text-align:right'],
                            ],
                            // html attributes for group summary row
                            'options' => ['class' => 'info table-info','style' => 'font-weight:bold;']
                        ];
                    },
                ],
                [
                    'attribute' => 'status_doc',
                    'filter' => $status,
                    'value' => function($data){
                        $status = [ Documento::GUIA_GENERADA => 'GUIA GENERADA', Documento::DOCUMENTO_GENERADO => 'GENERADO', Documento::DOCUMENTO_ANULADO => 'ANULADO'];
                        return $status[$data->status_doc];
                    },
                    'hAlign' => 'left',
                    'vAlign' => 'middle',
                    //'width' => '10%',
                ],
                [
                    'attribute' => 'statussunat_doc',
                    'hAlign' => 'center',
                    'vAlign' => 'middle',
                    //'width' => '10%',
                    'format' => 'raw',
                    'value' => function ($model) {

                        if (!$model->statussunat_doc){
                          return "<button class='btn btn-success btn-flat btn-xs'>Enviado</button>";
                        }
                        if ($model->statussunat_doc === -1 && $model->status_doc === Documento::DOCUMENTO_GENERADO){
                          return "<button class='btn btn-warning btn-flat btn-xs'>No enviado</button>";
                        }
                        if ($model->statussunat_doc > 0){
                          return "<button class='btn btn-danger btn-flat btn-xs'>No recibido</button>";
                        }

                        if ($model->statussunat_doc === -1 && $model->status_doc === Documento::DOCUMENTO_ANULADO){
                          return "<button class='btn btn-danger btn-flat btn-xs'>Anulado</button>";
                        }
                         // if ($model->statussunat_doc === -1) {
                         //     return 'x'; // "x" icon in red color
                         // } else {
                         //     return 'v'; // check icon
                         // }
                    },
                ],
                [
                  'label' => 'Subtotal',
                  'value' => function($model){
                      $total = $model->total_doc - $model->totalimp_doc;
                      return ($model->status_doc !== Documento::DOCUMENTO_ANULADO) ? ($model->tipo_doc === NotaCredito::TIPODOC_NCREDITO ? -1 * $total : $total) : 0;
                  },
                  'format' => ['decimal', 2],
                  //'width' => '10%',
                  'hAlign' => 'right',
                ],
                [
                  'attribute' => 'totalimp_doc',
                  'value' => function($data) {
                    return ($data->status_doc !== Documento::DOCUMENTO_ANULADO) ? ($data->tipo_doc === NotaCredito::TIPODOC_NCREDITO ? -1 * $data->totalimp_doc : $data->totalimp_doc) : '0';
                  },
                  'hAlign' => 'right',
                  //'width' => '10%',
                  'format' => ['decimal', 2],
                  'pageSummary' => true
                ],
                [
                  'attribute' => 'total_doc',
                  'value' => function($data) {
                    return ($data->status_doc !== Documento::DOCUMENTO_ANULADO) ? ($data->tipo_doc === NotaCredito::TIPODOC_NCREDITO ? -1 * $data->total_doc : $data->total_doc) : '0';
                  },
                  'hAlign' => 'right',
                  //'width' => '10%',
                  'pageSummary' => true,
                  'format' => ['decimal', 2],
                ],
                // 'total_doc',
                [
                    'class' => '\kartik\grid\ActionColumn',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'template' => '{print}&nbsp;&nbsp;{sunat}&nbsp;&nbsp;{guia} ',
                    'buttons' => [
                        'guia' => function($url, $model) {
                          $return = "";

                          if ($model->tipo_doc === Documento::TIPODOC_BOLETA || $model->tipo_doc === Documento::TIPODOC_FACTURA) {
                              $return = Html::a('<button class="btn btn-flat btn-xs btn-warning"><i class="fa fa-print"></i></button>',
                                        $url,
                                        [
                                            'title' => Yii::t('documento', 'Referral guide'). " "
                                                       .$model->guiaRem->numeracion->tipoDocumento->abrv_tipod
                                                       .$model->guiaRem->numeracion->serie_num."-"
                                                       .$model->guiaRem->cod_doc,
                                            'class' => 'pjax-print-document',
                                            'data' => [
                                                'id' => $model->id_doc,
                                            ]
                                        ]) ;
                         }

                          return $return;
                        },
                        'print' =>  function ($url, $model) {
                            return
                                Html::a('<button class="btn btn-flat btn-xs btn-primary"><i class="fa fa-print"></i></button>',
                                    $url,
                                    [
                                        'title' => Yii::t('app', 'Print'),
                                        'class' => 'pjax-print-document',
                                        'data' => [
                                            'id' => $model->id_doc,
                                        ]
                                    ]) ;
                        },
                        'sunat' =>  function ($url, $model) {
              							$return = "";
              							if ($model->statussunat_doc < 0 && $model->status_doc == $model::DOCUMENTO_GENERADO){

              								$return = Html::a('<button class="btn btn-flat btn-xs btn-success"><i class="fa fa-upload"></i></button>',
                                              $url,
                                              [
                                                  'title' => Yii::t('app', 'Send'). ' SUNAT',
                                                  'class' => 'pjax-send-sunat',
                                                  'data' => [
                                                      'id' => $model->id_doc,
                                                  ]
              								]);
              							} else {
              								if ($model->statussunat_doc === 0){
              									$return = Html::a('<button class="btn btn-flat btn-xs btn-success"><i class="fa fa-check"></i></button>',
              									'#',
              									[
              										'title' => Yii::t('app', 'Sended'). ' SUNAT',
              									]);
              								} else {
              									$return = Html::a('<button class="btn btn-flat btn-xs btn-danger"><i class="fa fa-ban"></i></button>',
                                                  "",
                                                  [
                                                      'title' => Yii::t('app', 'CANCELED'),
                                                      'class' => 'pjax-canceled',
                                                  ]);
              								}
              							}
                            return  $return;
                        },
                    ],
                    'urlCreator' => function ($action, $model) {
                        if ($action === 'guia') {
                            $id = $model->guiaRem->id_doc;
                            return Url::to(['documento/guia-rpt','id' => $id]);
                        }

                        if ($action === 'print') {
                            $url = "";
                            switch ($model->tipo_doc){
                              case Documento::TIPODOC_FACTURA:
                              case Documento::TIPODOC_BOLETA:
                                                        $url = 'documento/documento-rpt'; break;
                              case NotaCredito::TIPODOC_NCREDITO:
                                                        $url = 'nota-credito/nota-rpt'; break;
                            }
                            return Url::to([ $url ,'id' => $model->id_doc]);
                        }

                        if ($action === 'sunat') {
            							if ($model->tipo_doc === Documento::TIPODOC_FACTURA || $model->tipo_doc === Documento::TIPODOC_BOLETA) {
            								return Url::to(['documento/ajax-gen-fact-xml','id' => $model->id_doc]);
            							}
            							if ($model->tipo_doc === Documento::TIPODOC_NCREDITO ) {
            								return Url::to(['documento/ajax-gen-note-xml','id' => $model->id_doc]);
            							}
                        }
                    }
                ],

            ],
        ]); ?>
        <?php Pjax::end(); ?>
    </div>

<?php

$js = <<<JS
    $( 'body' ).on( 'click', '.pjax-print-document', function( e ){
        e.preventDefault();
        let url = $( this ).prop( 'href' );
        window.open( url,'_blank');
    });

    $( 'body' ).on( 'click', '.pjax-canceled', function( e ){
        e.preventDefault();
    });

    $( 'body' ).on( 'click', '.pjax-send-sunat', function( e ){
        e.preventDefault();
        let url = $( this ).prop( 'href' );
        //debugger;
        $.ajax({
            url: url,
            success: function(data){
                data = JSON.parse(data);
                if ( data.code == "0" ){
                    swal('Success',data.description,'success');
                } else {
                    swal('Warning',data.code + ' - ' + data.description,'warning');
                    return;
                }
                $.pjax.reload( '#grid', { timeout: 3000 } )

            },
            error: function(data){
                console.log(data);
            }
        });
    });

JS;
$this->registerJsVar( "buttonCreate", "" );
$this->registerJsVar( "buttonSubmit", "" );
$this->registerJsVar( "buttonCancel", "" );
$this->registerJsVar( "buttonPrint", "" );
$this->registerJsVar( "frameRpt", "" );
$this->registerJs( $js, View::POS_LOAD);

$js = <<<JS
function aplicarDateRangeFilter() {
  $('.grid-view').yiiGridView('applyFilter');
}
JS;
$this->registerJs( $js, View::POS_BEGIN);

echo   $this->render('//site/_modalForm',[]);
// $this->registerCss(".kv-grid-table{ width: 1200px !important; }");
