<?php
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use app\models\Cliente;
use app\models\Documento;
use app\models\TipoDocumento;
use app\models\NotaCredito;
use kartik\daterange\DateRangePicker;


/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = Yii::t('app', 'Product movement');
$this->params['breadcrumbs'][] = $this->title;
$status = [ 2 => 'DOCUMENTO GENERADO', 3 => 'DOCUMENTO ANULADO'];
$primerDiaMes = date('01/MM/yyyy'); // hard-coded '01' for first day
$ultimoDiaMes  = date('dd/MM/yyyy');
?>
<div class="documento-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(['id' => 'grid']); ?>

    <p><?php  echo $this->render('_searchKardex', ['model' => $searchModel]); ?></p>

	<?php
		$isFa = true;
		// $isFa below determines if export['fontAwesome'] property is set to true.
		$exportConfig = [
			GridView::EXCEL => [
				'label' => Yii::t('app', 'Excel'),
				'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
				'iconOptions' => ['class' => 'text-success'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('app', 'grid-export'),
				'alertMsg' => Yii::t('app', 'The EXCEL export file will be generated for download.'),
				'options' => ['title' => Yii::t('app', 'Microsoft Excel 95+')],
				'mime' => 'application/vnd.ms-excel',
				'config' => [
					'worksheet' => Yii::t('app', 'ExportWorksheet'),
					'cssFile' => ''
				]
			],
			GridView::PDF => [
				'label' => Yii::t('app', 'PDF'),
				'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
				'iconOptions' => ['class' => 'text-danger'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('app', 'grid-export'),
				'alertMsg' => Yii::t('app', 'The PDF export file will be generated for download.'),
				'options' => ['title' => Yii::t('app', 'Portable Document Format')],
				'mime' => 'application/pdf',
				'config' => [
					'mode' => 'c',
					'format' => 'A4-L',
					'destination' => 'I',
					'marginTop' => 20,
					'marginBottom' => 20,
					'cssInline' => '.kv-wrap{padding:20px;}' .
						'.kv-align-center{text-align:center;}' .
						'.kv-align-left{text-align:left;}' .
						'.kv-align-right{text-align:right;}' .
						'.kv-align-top{vertical-align:top!important;}' .
						'.kv-align-bottom{vertical-align:bottom!important;}' .
						'.kv-align-middle{vertical-align:middle!important;}' .
						'.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
						'.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
						'.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
					'methods' => [
						/*'SetHeader' => [
							['odd' => $pdfHeader, 'even' => $pdfHeader]
						],
						'SetFooter' => [
							['odd' => $pdfFooter, 'even' => $pdfFooter]
						],*/
					],
					'options' => [
						'title' => 'Title',
						'subject' => Yii::t('app', 'PDF export generated by kartik-v/yii2-grid extension'),
						'keywords' => Yii::t('app', 'krajee, grid, export, yii2-grid, pdf')
					],
					'contentBefore'=>'',
					'contentAfter'=>''
				]
			],

		];
	?>

    <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'pjax' => true,
        				'toolbar' => [
        					'{export}',
        					'{toggleData}'
        				],
        				//'fontAwesome' => $isFa,
        				'exportConfig' => $exportConfig,
        				'panel' => [
        					'heading'=>'<h3 class="panel-title"><i class="fa fa-book"></i> ' . Yii::t('app','Product movement') . '</h3>',
        					// 'type'=>'success',
        					// 'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> Create Country', ['create'], ['class' => 'btn btn-success']),
        					// 'after'=>Html::a('<i class="fa fa-refresh"></i> ' . Yii::t('app','Refresh '), ['listado-factura'], ['class' => 'btn btn-success']),
        					// 'footer'=>true,
        				],
                'showPageSummary' => true,
                'columns' => [
                          [
                            'attribute' => 'fecha_trans',
                            'format' => ['date', 'php:d/m/Y']
                          ],
                          [
                            'attribute' => 'docref_trans',
							              'label' => 'Documento',
                          ],
                          [
                            'attribute' => 'codigo_trans',
                            'label' => 'Codigo',
                          ],
                          [
                            'attribute' => 'ope_trans',
                            'label' => 'Operacion',
                          ],
                          [
                            'attribute' => 'des_tipom',
                            'label' => 'Movimiento',
                          ],
                          [
                            'attribute' => 'des_tipod',
                            'label' => 'Tipo documento',
                          ],
                          [
                            'attribute' => 'ingreso_unidades',
                            'label' => 'Ingreso',
                            'format' => ['decimal',2],
                            'width' => '5%',
                            'format' => ['decimal',2],
                            'hAlign' => 'right',
                            'pageSummary' => true,
                          ],
                          // 'moneda',
                          // [
                          //   'attribute' => 'precio_compra_ext',
                          //   'label' => 'P.Compra$',
                          //   'width' => '5%',
                          //   'format' => ['decimal',2],
                          //   'hAlign' => 'right',
                          // ],
                          // [
                          //   'attribute' => 'precio_compra_soles',
                          //   'label' => 'P.Compra/S',
                          //   'width' => '5%',
                          //   'format' => ['decimal',2],
                          //   'hAlign' => 'right',
                          // ],
                          // [
                          //   'attribute' => 'ingreso_valorizados',
                          //   'label' => 'I.Valorizados',
                          //   'format' => ['decimal',2],
                          //   'hAlign' => 'right',
                          // ],
                          [
                            'attribute' => 'salidas_unidades',
                            'value' => function( $data ) {
                                return $data['salidas_unidades'];
                            },
                            'label' => 'Salidas',
                            'width' => '5%',
                            'format' => ['decimal',2],
                            'hAlign' => 'right',
                            'pageSummary' => true,
            						  ],
            						  [
            							  'attribute' => 'saldo',
                            'format' => ['decimal',2],
                            'hAlign' => 'right',
            						  ]
                  ]
              ]);?>
        <?php Pjax::end(); ?>
</div>
<?php
// $this->registerCss(".kv-grid-table{ width: 1600px !important; }");
$this->registerJsVar( "buttonCreate", "" );
$this->registerJsVar( "buttonSubmit", "" );
$this->registerJsVar( "buttonCancel", "" );
$this->registerJsVar( "buttonPrint", "" );
$this->registerJsVar( "frameRpt", "" );
